default:
	@echo no default

.PHONY: bin/dircolors.hex
bin/dircolors.hex: hex2rgb.awk dircolors.hex
	@mkdir -p bin
	@rm -f $@
	@echo '#!/bin/sh'                                             >> $@
	@echo '# autogenerated - no questions buddy'                  >> $@
	@echo "HEX2RGB_AWK_SRC='$$(sed 's:\\n:\\\\n:g' hex2rgb.awk)'" >> $@
	@echo "$$(cat dircolors.hex)"                                 >> $@
	@chmod +x $@
